server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


