spring:
  data:
    mongodb:
      uri: mongodb+srv://pranshubisht:dPDrG4NeFiWznMJt@authentication-system.jknkql6.mongodb.net/?retryWrites=true&w=majority&appName=Authentication-System
      database: microservice
  application:
    name: RATING-SERVICE
server:
  port: 8083

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#    hostname: localhost